### ISSUE TITLE
Move to relay-tools organization?

### ISSUE THREAD

**Issue by taion** [relay-tools/relay-compiler-webpack-plugin#54]
We have a lot of other Relay tooling consolidated in https://github.com/relay-tools. I think it would make sense to move this repo here, if you're open to it.

**Comment by danielholmes** [comment]
@taion Yea I'm open to this - it makes sense. I haven't done this before, but it looks like i can transfer ownership - are there any other steps I should take?

**Comment by taion** [comment]
Nope, that's basically it.

**Comment by danielholmes** [comment]
@taion "You don’t have the permission to create public repositories on relay-tools" - so either you need to add me to relay-tools organisation, or maybe if I add you as a collaborator you'll have permission to move it? I've added you, let me know how you go

**Comment by taion** [comment]
Oops, added you!

**Comment by danielholmes** [comment]
@taion done
