### ISSUE TITLE
Cannot use together with relay-compiler-language-typescript

### ISSUE THREAD

**Issue by fazo96** [relay-tools/relay-compiler-webpack-plugin#64]
Hi, I have this problem when trying to install this together with the relay-compiler-language-typescript package:

```
npm i --save-dev relay-compiler-webpack-plugin
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: flexhire-react@1.0.0
npm ERR! Found: relay-compiler@11.0.2
npm ERR! node_modules/relay-compiler
npm ERR!   dev relay-compiler@"^11.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer relay-compiler@"^8.0.0" from relay-compiler-webpack-plugin@9.0.0
npm ERR! node_modules/relay-compiler-webpack-plugin
npm ERR!   dev relay-compiler-webpack-plugin@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/fazo/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fazo/.npm/_logs/2021-05-18T16_39_31_647Z-debug.log
```

This is due to this project requiring a peerDependency of `relay-compiler@^8.0.0` and relay-compiler-language-typescript requiring a peerDependency for `relay-compiler@>=10.1.3`

If you could switch the peerDependency requirement to `relay-compiter@>=8.0.0` the problem would be fixed, by allowing versions 9 and above of the relay-compiler to be used with this project

Assuming that won't break anything :smile: I wouldn't know

Without this project I have to manually run the relay compiler separately from my webpack dev server, so I would like to be able to integrate them

**Comment by danielholmes** [comment]
@fazo96 thanks for alerting me, I thought I had made that change but obviously not. Fixed in v9.1.0 just released
